//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_KAMPUS_MERDEKA.DAL.Edmx
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KampusMerdekaEntities : DbContext
    {
        public KampusMerdekaEntities()
            : base("name=KampusMerdekaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mMenu> mMenus { get; set; }
        public virtual DbSet<mModule> mModules { get; set; }
        public virtual DbSet<mParameter_Detail> mParameter_Detail { get; set; }
        public virtual DbSet<mParameter_Header> mParameter_Header { get; set; }
        public virtual DbSet<mRole> mRoles { get; set; }
        public virtual DbSet<mRoleAccess> mRoleAccesses { get; set; }
        public virtual DbSet<mSystemConfiguration> mSystemConfigurations { get; set; }
        public virtual DbSet<mSystemLanguage> mSystemLanguages { get; set; }
        public virtual DbSet<mUser> mUsers { get; set; }
        public virtual DbSet<mUserRole> mUserRoles { get; set; }
        public virtual DbSet<TrDebugEmail> TrDebugEmails { get; set; }
        public virtual DbSet<trDebugError> trDebugErrors { get; set; }
        public virtual DbSet<mKeyInDumping> mKeyInDumpings { get; set; }
        public virtual DbSet<mRFID_Tag> mRFID_Tag { get; set; }
    }
}
