//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_KAMPUS_MERDEKA.DAL.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class mKeyInDumping
    {
        public int intKeyInDumpingID { get; set; }
        public Nullable<int> intNoBO { get; set; }
        public string txtCharges { get; set; }
        public string txtNamaProduk { get; set; }
        public string txtPIC { get; set; }
        public string txtDumpingLine { get; set; }
        public string txtStartTime { get; set; }
        public string txtEndTime { get; set; }
        public string txtInsertedBy { get; set; }
        public Nullable<System.DateTime> dtmInsertedDate { get; set; }
        public string txtUpdatedBy { get; set; }
        public Nullable<System.DateTime> dtmUpdatedDate { get; set; }
        public string txtGUID { get; set; }
        public string txtStatus { get; set; }
    }
}
