//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_KAMPUS_MERDEKA.DAL.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class mParameter_Detail
    {
        public int intParameter_DetailID { get; set; }
        public Nullable<int> intParameter_HeaderID { get; set; }
        public string txtCode { get; set; }
        public string txtDesc { get; set; }
        public Nullable<bool> bitActive { get; set; }
        public string txtGUID { get; set; }
    
        public virtual mParameter_Header mParameter_Header { get; set; }
    }
}
