//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_KAMPUS_MERDEKA.DAL.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class mUserRole
    {
        public int intUserRoleID { get; set; }
        public int intRoleID { get; set; }
        public int intUserID { get; set; }
        public string txtInsertedBy { get; set; }
        public Nullable<System.DateTime> dtmInsertedDate { get; set; }
        public string txtUpdatedBy { get; set; }
        public Nullable<System.DateTime> dtmUpdatedDate { get; set; }
        public string txtGUID { get; set; }
    }
}
