//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_KAMPUS_MERDEKA.DAL.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class trDebugError
    {
        public string txtId { get; set; }
        public string txtDebugName { get; set; }
        public string txtErrorInfo { get; set; }
        public System.DateTime dtmErrorDate { get; set; }
        public string txtStackTrace { get; set; }
    }
}
