//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_KAMPUS_MERDEKA.DAL.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrDebugEmail
    {
        public int intDebugEmailID { get; set; }
        public string txtFrom { get; set; }
        public string txtTo { get; set; }
        public string txtCC { get; set; }
        public string txtBCC { get; set; }
        public string txtSubject { get; set; }
        public string txtPriority { get; set; }
        public Nullable<short> bitIsBodyHTML { get; set; }
        public string txtBody { get; set; }
        public string txtInsertedBy { get; set; }
        public Nullable<System.DateTime> dtmInsertedDate { get; set; }
        public string txtUpdatedBy { get; set; }
        public Nullable<System.DateTime> dtmUpdatedDate { get; set; }
        public string txtGUID { get; set; }
    }
}
